language: node_js
node_js:
  - '10'
sudo: required
services:
  - docker
  - mongodb
script:
  - npm run test
deploy:
  provider: gae
  project: order-api-226821
  keyfile: gce.json
  skip_cleanup: true
  verbosity: debug
  on: master
before_install:
  - openssl aes-256-cbc -K $encrypted_5c02ebcbdbd5_key -iv $encrypted_5c02ebcbdbd5_iv
    -in gce.json.enc -out gce.json -d
